-- Generated by scripts/generate-catalog-seed.mjs.
-- Source snapshot SHA-256: 87a2d9c43272ec7fa78db0927d65277cab0aa2c7a1dcf1937ed50b3932e03ee1
-- Import decisions SHA-256: 26319b0f2365254e5770dede9d1e8d63f99ff585d366cc5b32ed7c502edb1862

PRAGMA foreign_keys = ON;

CREATE TEMP TABLE _serrian_tide_creature_seed (
  ordinal INTEGER PRIMARY KEY, source_external_id TEXT NOT NULL UNIQUE, name TEXT NOT NULL,
  challenge_rating REAL, encounter_scale TEXT NOT NULL, type TEXT NOT NULL, role TEXT NOT NULL,
  size TEXT NOT NULL, description_short TEXT NOT NULL, hp_total REAL, initiative REAL, armor_soak REAL,
  magic_resonance_interaction TEXT NOT NULL, behavior_tactics TEXT NOT NULL, habitat TEXT NOT NULL,
  diet TEXT NOT NULL, loot_harvest TEXT NOT NULL, story_hooks TEXT NOT NULL, notes TEXT NOT NULL
);
INSERT INTO _serrian_tide_creature_seed VALUES
  (0, 'creature:bat', 'Bat', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (1, 'creature:camel', 'Camel', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (2, 'creature:cat', 'Cat', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (3, 'creature:cattle', 'Cattle', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (4, 'creature:chicken', 'Chicken', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (5, 'creature:crow', 'Crow', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (6, 'creature:domestic-dog', 'Domestic Dog', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (7, 'creature:donkey', 'Donkey', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (8, 'creature:dove', 'Dove', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (9, 'creature:eagle', 'Eagle', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (10, 'creature:elephant', 'Elephant', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (11, 'creature:falcon', 'Falcon', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (12, 'creature:ferret', 'Ferret', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (13, 'creature:fox', 'Fox', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (14, 'creature:goat', 'Goat', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (15, 'creature:hawk', 'Hawk', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (16, 'creature:horse', 'Horse', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (17, 'creature:lizard', 'Lizard', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (18, 'creature:monkey', 'Monkey', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (19, 'creature:mouse', 'Mouse', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (20, 'creature:mule', 'Mule', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (21, 'creature:owl', 'Owl', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (22, 'creature:ox', 'Ox', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (23, 'creature:parrot', 'Parrot', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (24, 'creature:pig', 'Pig', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (25, 'creature:pigeon', 'Pigeon', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (26, 'creature:rabbit', 'Rabbit', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (27, 'creature:rat', 'Rat', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (28, 'creature:raven', 'Raven', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (29, 'creature:scorpion', 'Scorpion', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (30, 'creature:sea-otter', 'Sea Otter', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (31, 'creature:sea-turtle', 'Sea Turtle', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (32, 'creature:seagull', 'Seagull', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (33, 'creature:snake', 'Snake', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (34, 'creature:spider', 'Spider', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', ''),
  (35, 'creature:wolf', 'Wolf', NULL, '', 'Animal', '', '', '', NULL, NULL, NULL, '', '', '', '', '', '', '');
INSERT OR IGNORE INTO creatures (
  name, challenge_rating, encounter_scale, type, role, size, description_short, hp_total, initiative,
  armor_soak, magic_resonance_interaction, behavior_tactics, habitat, diet, loot_harvest, story_hooks,
  notes, created_by_user_id, source_system, source_external_id
)
SELECT name, challenge_rating, encounter_scale, type, role, size, description_short, hp_total, initiative,
  armor_soak, magic_resonance_interaction, behavior_tactics, habitat, diet, loot_harvest, story_hooks,
  notes, NULL, 'serrian-tide-canonical-catalog', source_external_id
FROM _serrian_tide_creature_seed ORDER BY ordinal;

CREATE TEMP TABLE _serrian_tide_creature_genre_seed (ordinal INTEGER PRIMARY KEY, creature_external_id TEXT NOT NULL, genre_tag TEXT NOT NULL, sort_order INTEGER NOT NULL);
INSERT INTO _serrian_tide_creature_genre_seed VALUES
  (0, 'creature:bat', 'Horror', 0),
  (100, 'creature:camel', 'Fantasy', 0),
  (101, 'creature:camel', 'Post-Apoc', 1),
  (200, 'creature:cat', 'Horror', 0),
  (201, 'creature:cat', 'Fantasy', 1),
  (202, 'creature:cat', 'Universal', 2),
  (203, 'creature:cat', 'Modern', 3),
  (300, 'creature:cattle', 'Western', 0),
  (600, 'creature:domestic-dog', 'Fantasy', 0),
  (601, 'creature:domestic-dog', 'Universal', 1),
  (602, 'creature:domestic-dog', 'Horror', 2),
  (603, 'creature:domestic-dog', 'Apocalyptic', 3),
  (604, 'creature:domestic-dog', 'Modern', 4),
  (605, 'creature:domestic-dog', 'Military/War', 5),
  (606, 'creature:domestic-dog', 'Medieval Fantasy', 6),
  (607, 'creature:domestic-dog', 'Western', 7),
  (700, 'creature:donkey', 'Fantasy', 0),
  (1100, 'creature:falcon', 'Fantasy', 0),
  (1101, 'creature:falcon', 'Universal', 1),
  (1102, 'creature:falcon', 'Military/War', 2),
  (1200, 'creature:ferret', 'Fantasy', 0),
  (1201, 'creature:ferret', 'Steampunk', 1),
  (1400, 'creature:goat', 'Fantasy', 0),
  (1500, 'creature:hawk', 'Fantasy', 0),
  (1501, 'creature:hawk', 'Apocalyptic', 1),
  (1502, 'creature:hawk', 'Military/War', 2),
  (1600, 'creature:horse', 'Horror', 0),
  (1601, 'creature:horse', 'Fantasy', 1),
  (1602, 'creature:horse', 'Universal', 2),
  (1603, 'creature:horse', 'Military/War', 3),
  (1604, 'creature:horse', 'Western', 4),
  (1605, 'creature:horse', 'High Fantasy', 5),
  (1606, 'creature:horse', 'Medieval Fantasy', 6),
  (2000, 'creature:mule', 'Fantasy', 0),
  (2001, 'creature:mule', 'Western', 1),
  (2002, 'creature:mule', 'Apocalyptic', 2),
  (2003, 'creature:mule', 'Medieval Fantasy', 3),
  (2100, 'creature:owl', 'Fantasy', 0),
  (2101, 'creature:owl', 'Horror', 1),
  (2200, 'creature:ox', 'Western', 0),
  (2500, 'creature:pigeon', 'Steampunk', 0),
  (2501, 'creature:pigeon', 'Medieval Fantasy', 1),
  (2502, 'creature:pigeon', 'Renaissance', 2),
  (2600, 'creature:rabbit', 'Modern', 0),
  (2700, 'creature:rat', 'Horror', 0),
  (2800, 'creature:raven', 'Fantasy', 0),
  (2801, 'creature:raven', 'Horror', 1),
  (2900, 'creature:scorpion', 'Horror', 0),
  (3300, 'creature:snake', 'Horror', 0),
  (3500, 'creature:wolf', 'High Fantasy', 0);
INSERT OR IGNORE INTO creature_genre_tags (creature_id, genre_tag, sort_order)
SELECT creature.id, seed.genre_tag, seed.sort_order FROM _serrian_tide_creature_genre_seed seed
JOIN creatures creature ON creature.source_system = 'serrian-tide-canonical-catalog' AND creature.source_external_id = seed.creature_external_id
ORDER BY seed.ordinal;
DROP TABLE _serrian_tide_creature_genre_seed;

CREATE TEMP TABLE _serrian_tide_creature_use_seed (ordinal INTEGER PRIMARY KEY, creature_external_id TEXT NOT NULL, use_type TEXT NOT NULL, sort_order INTEGER NOT NULL);
INSERT INTO _serrian_tide_creature_use_seed VALUES
  (100, 'creature:camel', 'Mount', 0),
  (200, 'creature:cat', 'Pet', 0),
  (600, 'creature:domestic-dog', 'Mount', 0),
  (700, 'creature:donkey', 'Mount', 0),
  (800, 'creature:dove', 'Mount', 0),
  (1000, 'creature:elephant', 'Mount', 0),
  (1100, 'creature:falcon', 'Mount', 0),
  (1400, 'creature:goat', 'Mount', 0),
  (1600, 'creature:horse', 'Mount', 0),
  (1700, 'creature:lizard', 'Companion', 0),
  (2000, 'creature:mule', 'Mount', 0),
  (2200, 'creature:ox', 'Mount', 0),
  (2300, 'creature:parrot', 'Mount', 0),
  (2700, 'creature:rat', 'Pet', 0),
  (2701, 'creature:rat', 'Companion', 1),
  (2800, 'creature:raven', 'Mount', 0),
  (2801, 'creature:raven', 'Companion', 1),
  (3100, 'creature:sea-turtle', 'Mount', 0),
  (3500, 'creature:wolf', 'Mount', 0),
  (3501, 'creature:wolf', 'Companion', 1);
INSERT OR IGNORE INTO creature_uses (creature_id, use_type, notes, sort_order)
SELECT creature.id, seed.use_type, '', seed.sort_order FROM _serrian_tide_creature_use_seed seed
JOIN creatures creature ON creature.source_system = 'serrian-tide-canonical-catalog' AND creature.source_external_id = seed.creature_external_id
ORDER BY seed.ordinal;
DROP TABLE _serrian_tide_creature_use_seed;

DROP TABLE _serrian_tide_creature_seed;
