import { useEffect, useState } from "react";
import type { CreatureCoreDraft, CreatureItemCandidate, CreatureSkillCandidate, SaveCreatureAggregate } from "../../types/creature";

const numeric = (value: string) => value === "" ? null : Number(value);
const move = <T,>(rows: T[], index: number, direction: -1 | 1) => {
  const target = index + direction;
  if (target < 0 || target >= rows.length) return rows;
  const next = [...rows]; [next[index], next[target]] = [next[target], next[index]]; return next;
};
function RowActions({ index, length, onMove, onRemove }: { index: number; length: number; onMove: (direction: -1 | 1) => void; onRemove: () => void }) {
  return <div className="creature-row__actions"><button type="button" disabled={index === 0} onClick={() => onMove(-1)}>↑</button><button type="button" disabled={index === length - 1} onClick={() => onMove(1)}>↓</button><button className="is-danger" type="button" onClick={onRemove}>Remove</button></div>;
}

export function CreatureOverviewEditor({ draft, onChange }: { draft: SaveCreatureAggregate; onChange: (draft: SaveCreatureAggregate) => void }) {
  const setCore = (update: Partial<CreatureCoreDraft>) => onChange({ ...draft, core: { ...draft.core, ...update } });
  return <div className="creature-tab"><div className="skill-editor__intro"><p>Identity and classification stay flexible so future modules can extend the catalog without schema redesign.</p></div><div className="creature-form-grid">
    <label className="is-wide"><span>Name</span><input value={draft.core.name} onChange={(event) => setCore({ name: event.target.value })} /></label>
    <label><span>Challenge Rating</span><input type="number" value={draft.core.challengeRating ?? ""} placeholder="Unknown" onChange={(event) => setCore({ challengeRating: numeric(event.target.value) })} /></label>
    <label><span>Encounter Scale</span><input value={draft.core.encounterScale} onChange={(event) => setCore({ encounterScale: event.target.value })} /></label>
    <label><span>Type</span><input value={draft.core.type} onChange={(event) => setCore({ type: event.target.value })} /></label>
    <label><span>Role</span><input value={draft.core.role} onChange={(event) => setCore({ role: event.target.value })} /></label>
    <label><span>Size</span><input value={draft.core.size} onChange={(event) => setCore({ size: event.target.value })} /></label>
    <label className="is-wide"><span>Short Description</span><textarea value={draft.core.descriptionShort} onChange={(event) => setCore({ descriptionShort: event.target.value })} /></label>
  </div><RepeatText title="Alt Names" label="Alt Name" values={draft.altNames.map((row) => row.altName)} onChange={(values) => onChange({ ...draft, altNames: values.map((altName, sortOrder) => ({ altName, sortOrder })) })} /><RepeatText title="Genre Tags" label="Genre" values={draft.genreTags.map((row) => row.genreTag)} onChange={(values) => onChange({ ...draft, genreTags: values.map((genreTag, sortOrder) => ({ genreTag, sortOrder })) })} /></div>;
}

function RepeatText({ title, label, values, onChange }: { title: string; label: string; values: string[]; onChange: (values: string[]) => void }) {
  return <section className="creature-repeat"><div className="creature-section-heading"><h3>{title}</h3><button type="button" onClick={() => onChange([...values, ""])}>Add</button></div>{values.map((value, index) => <div className="creature-row creature-row--short" key={index}><label><span>{label}</span><input value={value} onChange={(event) => onChange(values.map((entry, target) => target === index ? event.target.value : entry))} /></label><RowActions index={index} length={values.length} onMove={(direction) => onChange(move(values, index, direction))} onRemove={() => onChange(values.filter((_, target) => target !== index))} /></div>)}</section>;
}

export function CreatureMechanicsEditor({ draft, onChange }: { draft: SaveCreatureAggregate; onChange: (draft: SaveCreatureAggregate) => void }) {
  return <div className="creature-tab"><div className="skill-editor__intro"><p>Attributes and movement modes are repeatable. STR, DEX, CON, INT, WIS, and CHR are familiar keys, but ENERGON and other module attributes are equally valid.</p></div><section className="creature-repeat"><div className="creature-section-heading"><h3>Attributes</h3><button type="button" onClick={() => onChange({ ...draft, attributes: [...draft.attributes, { attributeKey: "", value: 0, notes: "", sortOrder: draft.attributes.length }] })}>Add Attribute</button></div>{draft.attributes.map((row, index) => <div className="creature-row" key={index}><label><span>Attribute</span><input value={row.attributeKey} onChange={(event) => onChange({ ...draft, attributes: draft.attributes.map((entry, target) => target === index ? { ...entry, attributeKey: event.target.value } : entry) })} /></label><label><span>Value</span><input type="number" value={row.value} onChange={(event) => onChange({ ...draft, attributes: draft.attributes.map((entry, target) => target === index ? { ...entry, value: Number(event.target.value) } : entry) })} /></label><label className="is-wide"><span>Notes</span><input value={row.notes} onChange={(event) => onChange({ ...draft, attributes: draft.attributes.map((entry, target) => target === index ? { ...entry, notes: event.target.value } : entry) })} /></label><RowActions index={index} length={draft.attributes.length} onMove={(direction) => onChange({ ...draft, attributes: move(draft.attributes, index, direction) })} onRemove={() => onChange({ ...draft, attributes: draft.attributes.filter((_, target) => target !== index) })} /></div>)}</section>
    <section className="creature-repeat"><div className="creature-section-heading"><h3>Movement Modes</h3><button type="button" onClick={() => onChange({ ...draft, movementModes: [...draft.movementModes, { movementMode: "", baseValue: 0, notes: "", sortOrder: draft.movementModes.length }] })}>Add Movement</button></div>{draft.movementModes.map((row, index) => <div className="creature-row" key={index}><label><span>Movement Mode</span><input value={row.movementMode} onChange={(event) => onChange({ ...draft, movementModes: draft.movementModes.map((entry, target) => target === index ? { ...entry, movementMode: event.target.value } : entry) })} /></label><label><span>Base Value</span><input type="number" value={row.baseValue} onChange={(event) => onChange({ ...draft, movementModes: draft.movementModes.map((entry, target) => target === index ? { ...entry, baseValue: Number(event.target.value) } : entry) })} /></label><label className="is-wide"><span>Notes</span><input value={row.notes} onChange={(event) => onChange({ ...draft, movementModes: draft.movementModes.map((entry, target) => target === index ? { ...entry, notes: event.target.value } : entry) })} /></label><RowActions index={index} length={draft.movementModes.length} onMove={(direction) => onChange({ ...draft, movementModes: move(draft.movementModes, index, direction) })} onRemove={() => onChange({ ...draft, movementModes: draft.movementModes.filter((_, target) => target !== index) })} /></div>)}</section></div>;
}

export function CreatureHealthEditor({ draft, onChange }: { draft: SaveCreatureAggregate; onChange: (draft: SaveCreatureAggregate) => void }) {
  const setCore = (update: Partial<CreatureCoreDraft>) => onChange({ ...draft, core: { ...draft.core, ...update } });
  return <div className="creature-tab"><div className="skill-editor__intro"><p>Totals and locations are independent source fields. No synchronization formula is assumed.</p></div><div className="creature-form-grid"><label><span>HP Total</span><input type="number" value={draft.core.hpTotal ?? ""} placeholder="Unknown" onChange={(event) => setCore({ hpTotal: numeric(event.target.value) })} /></label><label><span>Initiative</span><input type="number" value={draft.core.initiative ?? ""} placeholder="Unknown" onChange={(event) => setCore({ initiative: numeric(event.target.value) })} /></label><label><span>Armor Soak</span><input type="number" value={draft.core.armorSoak ?? ""} placeholder="Unknown" onChange={(event) => setCore({ armorSoak: numeric(event.target.value) })} /></label></div><section className="creature-repeat"><div className="creature-section-heading"><h3>HP Locations</h3><button type="button" onClick={() => onChange({ ...draft, hpLocations: [...draft.hpLocations, { locationName: "", hpValue: 0, notes: "", sortOrder: draft.hpLocations.length }] })}>Add Location</button></div>{draft.hpLocations.map((row, index) => <div className="creature-row" key={index}><label><span>Location</span><input value={row.locationName} onChange={(event) => onChange({ ...draft, hpLocations: draft.hpLocations.map((entry, target) => target === index ? { ...entry, locationName: event.target.value } : entry) })} /></label><label><span>HP</span><input type="number" value={row.hpValue} onChange={(event) => onChange({ ...draft, hpLocations: draft.hpLocations.map((entry, target) => target === index ? { ...entry, hpValue: Number(event.target.value) } : entry) })} /></label><label className="is-wide"><span>Notes</span><input value={row.notes} onChange={(event) => onChange({ ...draft, hpLocations: draft.hpLocations.map((entry, target) => target === index ? { ...entry, notes: event.target.value } : entry) })} /></label><RowActions index={index} length={draft.hpLocations.length} onMove={(direction) => onChange({ ...draft, hpLocations: move(draft.hpLocations, index, direction) })} onRemove={() => onChange({ ...draft, hpLocations: draft.hpLocations.filter((_, target) => target !== index) })} /></div>)}</section></div>;
}

export function CreatureAttacksEditor({ draft, onChange }: { draft: SaveCreatureAggregate; onChange: (draft: SaveCreatureAggregate) => void }) {
  return <div className="creature-tab"><div className="skill-editor__intro"><p>Each attack is stored independently. Unknown damage stays blank; an explicit zero remains zero.</p></div><section className="creature-repeat"><div className="creature-section-heading"><h3>Attacks</h3><button type="button" onClick={() => onChange({ ...draft, attacks: [...draft.attacks, { name: "", damage: null, rangeText: "", effect: "", notes: "", sortOrder: draft.attacks.length }] })}>Add Attack</button></div>{draft.attacks.map((row, index) => <div className="creature-row creature-row--attack" key={index}><label><span>Attack Name</span><input value={row.name} onChange={(event) => onChange({ ...draft, attacks: draft.attacks.map((entry, target) => target === index ? { ...entry, name: event.target.value } : entry) })} /></label><label><span>Damage</span><input type="number" value={row.damage ?? ""} placeholder="Unknown" onChange={(event) => onChange({ ...draft, attacks: draft.attacks.map((entry, target) => target === index ? { ...entry, damage: numeric(event.target.value) } : entry) })} /></label><label><span>Range</span><input value={row.rangeText} onChange={(event) => onChange({ ...draft, attacks: draft.attacks.map((entry, target) => target === index ? { ...entry, rangeText: event.target.value } : entry) })} /></label><label className="is-wide"><span>Effect</span><textarea value={row.effect} onChange={(event) => onChange({ ...draft, attacks: draft.attacks.map((entry, target) => target === index ? { ...entry, effect: event.target.value } : entry) })} /></label><label className="is-wide"><span>Notes</span><textarea value={row.notes} onChange={(event) => onChange({ ...draft, attacks: draft.attacks.map((entry, target) => target === index ? { ...entry, notes: event.target.value } : entry) })} /></label><RowActions index={index} length={draft.attacks.length} onMove={(direction) => onChange({ ...draft, attacks: move(draft.attacks, index, direction) })} onRemove={() => onChange({ ...draft, attacks: draft.attacks.filter((_, target) => target !== index) })} /></div>)}</section></div>;
}

function SkillLinkSection({ title, linkType, classification, draft, onChange, findSkills }: { title: string; linkType: "Skill" | "Granted"; classification?: string; draft: SaveCreatureAggregate; onChange: (draft: SaveCreatureAggregate) => void; findSkills: (search: string, classification?: string) => Promise<CreatureSkillCandidate[]> }) {
  const [search, setSearch] = useState(""); const [results, setResults] = useState<CreatureSkillCandidate[]>([]);
  useEffect(() => { if (!search.trim()) { setResults([]); return; } let active = true; const timeout = window.setTimeout(() => void findSkills(search, classification).then((rows) => { if (active) setResults(rows); }).catch(() => { if (active) setResults([]); }), 180); return () => { active = false; window.clearTimeout(timeout); }; }, [search, classification, findSkills]);
  const links = draft.skillLinks.filter((row) => row.linkType === linkType);
  return <section className="creature-repeat"><div className="creature-section-heading"><h3>{title}</h3><span>{links.length} linked</span></div><div className="creature-search-picker"><input type="search" value={search} placeholder={`Search existing ${title}`} onChange={(event) => setSearch(event.target.value)} />{results.length > 0 && <div className="creature-search-picker__results">{results.map((skill) => <button type="button" key={skill.id} disabled={draft.skillLinks.some((link) => link.skillId === skill.id && link.linkType === linkType)} onClick={() => { onChange({ ...draft, skillLinks: [...draft.skillLinks, { skillId: skill.id, skillName: skill.name, skillClassification: skill.classification, linkType, value: null, notes: "", sortOrder: links.length }] }); setSearch(""); setResults([]); }}>{skill.name}<span>{skill.classification}{skill.tier === null ? "" : ` · Tier ${skill.tier}`}</span></button>)}</div>}</div>{links.map((row) => { const index = draft.skillLinks.indexOf(row); return <div className="creature-row creature-row--skill" key={`${row.skillId}-${linkType}`}><div><strong>{row.skillName}</strong><span>{row.skillClassification}</span></div><label><span>Value</span><input type="number" value={row.value ?? ""} placeholder="None" onChange={(event) => onChange({ ...draft, skillLinks: draft.skillLinks.map((entry, target) => target === index ? { ...entry, value: numeric(event.target.value) } : entry) })} /></label><label><span>Notes</span><input value={row.notes} onChange={(event) => onChange({ ...draft, skillLinks: draft.skillLinks.map((entry, target) => target === index ? { ...entry, notes: event.target.value } : entry) })} /></label><button className="is-danger" type="button" onClick={() => onChange({ ...draft, skillLinks: draft.skillLinks.filter((_, target) => target !== index) })}>Unlink</button></div>; })}</section>;
}

export function CreatureSkillsEditor({ draft, onChange, findSkills }: { draft: SaveCreatureAggregate; onChange: (draft: SaveCreatureAggregate) => void; findSkills: (search: string, classification?: string) => Promise<CreatureSkillCandidate[]> }) {
  return <div className="creature-tab"><div className="skill-editor__intro"><p>Both sections resolve against the canonical Skill Library. Granted abilities are restricted to Special Ability Skills.</p></div><SkillLinkSection title="Skills" linkType="Skill" draft={draft} onChange={onChange} findSkills={findSkills} /><SkillLinkSection title="Granted / Special Abilities" linkType="Granted" classification="special ability" draft={draft} onChange={onChange} findSkills={findSkills} /></div>;
}

export function CreatureBehaviorEditor({ draft, onChange }: { draft: SaveCreatureAggregate; onChange: (draft: SaveCreatureAggregate) => void }) {
  const setCore = (update: Partial<CreatureCoreDraft>) => onChange({ ...draft, core: { ...draft.core, ...update } });
  const fields: [string, keyof CreatureCoreDraft][] = [["Magic / Resonance Interaction", "magicResonanceInteraction"], ["Behavior / Tactics", "behaviorTactics"], ["Habitat", "habitat"], ["Diet", "diet"], ["Loot / Harvest", "lootHarvest"], ["Story Hooks", "storyHooks"], ["Notes", "notes"]];
  return <div className="creature-tab"><div className="skill-editor__intro"><p>Behavior and ecology remain descriptive. This pass does not create combat or loot engines.</p></div><div className="creature-form-grid">{fields.map(([label, key]) => <label className="is-wide" key={key}><span>{label}</span><textarea value={String(draft.core[key] ?? "")} onChange={(event) => setCore({ [key]: event.target.value })} /></label>)}</div></div>;
}

export function CreatureVariantsEditor({ draft, onChange }: { draft: SaveCreatureAggregate; onChange: (draft: SaveCreatureAggregate) => void }) {
  return <div className="creature-tab"><section className="creature-repeat"><div className="creature-section-heading"><h3>Variants</h3><button type="button" onClick={() => onChange({ ...draft, variants: [...draft.variants, { name: "", description: "", notes: "", sortOrder: draft.variants.length }] })}>Add Variant</button></div>{draft.variants.map((row, index) => <div className="creature-row" key={index}><label><span>Name</span><input value={row.name} onChange={(event) => onChange({ ...draft, variants: draft.variants.map((entry, target) => target === index ? { ...entry, name: event.target.value } : entry) })} /></label><label className="is-wide"><span>Description</span><textarea value={row.description} onChange={(event) => onChange({ ...draft, variants: draft.variants.map((entry, target) => target === index ? { ...entry, description: event.target.value } : entry) })} /></label><label className="is-wide"><span>Notes</span><input value={row.notes} onChange={(event) => onChange({ ...draft, variants: draft.variants.map((entry, target) => target === index ? { ...entry, notes: event.target.value } : entry) })} /></label><RowActions index={index} length={draft.variants.length} onMove={(direction) => onChange({ ...draft, variants: move(draft.variants, index, direction) })} onRemove={() => onChange({ ...draft, variants: draft.variants.filter((_, target) => target !== index) })} /></div>)}</section><section className="creature-repeat"><div className="creature-section-heading"><h3>Creature Uses</h3><button type="button" onClick={() => onChange({ ...draft, uses: [...draft.uses, { useType: "", notes: "", sortOrder: draft.uses.length }] })}>Add Use</button></div><p className="creature-policy-note">Mount, Pet, and Companion are characteristics only. They do not make a Creature purchasable.</p>{draft.uses.map((row, index) => <div className="creature-row creature-row--short" key={index}><label><span>Use Type</span><input list="creature-use-values" value={row.useType} onChange={(event) => onChange({ ...draft, uses: draft.uses.map((entry, target) => target === index ? { ...entry, useType: event.target.value } : entry) })} /><datalist id="creature-use-values"><option value="Mount" /><option value="Pet" /><option value="Companion" /></datalist></label><label><span>Notes</span><input value={row.notes} onChange={(event) => onChange({ ...draft, uses: draft.uses.map((entry, target) => target === index ? { ...entry, notes: event.target.value } : entry) })} /></label><RowActions index={index} length={draft.uses.length} onMove={(direction) => onChange({ ...draft, uses: move(draft.uses, index, direction) })} onRemove={() => onChange({ ...draft, uses: draft.uses.filter((_, target) => target !== index) })} /></div>)}</section></div>;
}

export function CreaturePurchaseEditor({ draft, onChange, findItems }: { draft: SaveCreatureAggregate; onChange: (draft: SaveCreatureAggregate) => void; findItems: (search: string) => Promise<CreatureItemCandidate[]> }) {
  const [search, setSearch] = useState(""); const [results, setResults] = useState<CreatureItemCandidate[]>([]); const [viewItemId, setViewItemId] = useState<number | null>(null);
  useEffect(() => { if (!search.trim()) { setResults([]); return; } let active = true; const timeout = window.setTimeout(() => void findItems(search).then((rows) => { if (active) setResults(rows); }).catch(() => { if (active) setResults([]); }), 180); return () => { active = false; window.clearTimeout(timeout); }; }, [search, findItems]);
  return <div className="creature-tab"><div className="skill-editor__intro"><p>Purchasability exists only through an explicit Purchase relationship. Price and catalog information remain on the universal Item.</p></div><div className="creature-search-picker"><input type="search" value={search} placeholder="Link Existing Inventory Item" onChange={(event) => setSearch(event.target.value)} />{results.length > 0 && <div className="creature-search-picker__results">{results.map((item) => <button type="button" key={item.id} disabled={draft.purchaseItemLinks.some((link) => link.itemId === item.id)} onClick={() => { onChange({ ...draft, purchaseItemLinks: [...draft.purchaseItemLinks, { itemId: item.id, itemName: item.name, costCredits: item.costCredits, category: item.category, subtype: item.subtype, genreTags: item.genreTags, relationship: "Purchase", notes: "" }] }); setSearch(""); setResults([]); }}>{item.name}<span>{item.costCredits === null ? "Cost unknown" : `${item.costCredits.toLocaleString()} credits`} · {item.category}</span></button>)}</div>}</div><section className="creature-repeat"><div className="creature-section-heading"><h3>Linked Purchase Items</h3><span>{draft.purchaseItemLinks.length} listings</span></div>{!draft.purchaseItemLinks.length && <p className="creature-policy-note">This Creature is not currently purchasable.</p>}{draft.purchaseItemLinks.map((row, index) => <article className="creature-purchase-row" key={row.itemId}><div><strong>{row.itemName}</strong><span>{row.costCredits === null ? "Cost unknown" : `${row.costCredits.toLocaleString()} credits`} · {row.category}{row.subtype ? ` · ${row.subtype}` : ""}</span></div><div className="creature-purchase-row__actions"><button type="button" onClick={() => setViewItemId(viewItemId === row.itemId ? null : row.itemId)}>{viewItemId === row.itemId ? "Close" : "View Item"}</button><button className="is-danger" type="button" onClick={() => onChange({ ...draft, purchaseItemLinks: draft.purchaseItemLinks.filter((_, target) => target !== index) })}>Unlink</button></div>{viewItemId === row.itemId && <dl><div><dt>Category</dt><dd>{row.category || "Not set"}</dd></div><div><dt>Subtype</dt><dd>{row.subtype || "Not set"}</dd></div><div><dt>Genres</dt><dd>{row.genreTags.join(", ") || "None"}</dd></div></dl>}</article>)}</section></div>;
}

export function CreaturePreview({ draft }: { draft: SaveCreatureAggregate }) {
  const core = draft.core;
  return <article className="skill-preview creature-preview"><header><p>{core.type || "CREATURE"}</p><h3>{core.name || "Untitled Creature"}</h3><span>{[core.role, core.size, core.encounterScale].filter(Boolean).join(" · ") || "Classification incomplete"}</span></header>{core.descriptionShort && <p className="creature-preview__lead">{core.descriptionShort}</p>}<dl className="skill-preview__facts creature-preview__facts"><div><dt>Challenge</dt><dd>{core.challengeRating ?? "Unknown"}</dd></div><div><dt>HP Total</dt><dd>{core.hpTotal ?? "Unknown"}</dd></div><div><dt>Initiative</dt><dd>{core.initiative ?? "Unknown"}</dd></div><div><dt>Armor Soak</dt><dd>{core.armorSoak ?? "Unknown"}</dd></div></dl>
    <PreviewSection title="Identity" empty={!draft.altNames.length && !draft.genreTags.length}><p>Alt Names: {draft.altNames.map((row) => row.altName).filter(Boolean).join(", ") || "None"}</p><p>Genres: {draft.genreTags.map((row) => row.genreTag).filter(Boolean).join(", ") || "None"}</p></PreviewSection>
    <PreviewRows title="Attributes" rows={draft.attributes.map((row) => `${row.attributeKey}: ${row.value}${row.notes ? ` — ${row.notes}` : ""}`)} />
    <PreviewRows title="Movement" rows={draft.movementModes.map((row) => `${row.movementMode}: ${row.baseValue}${row.notes ? ` — ${row.notes}` : ""}`)} />
    <PreviewRows title="HP Locations" rows={draft.hpLocations.map((row) => `${row.locationName}: ${row.hpValue}${row.notes ? ` — ${row.notes}` : ""}`)} />
    <PreviewRows title="Attacks" rows={draft.attacks.map((row) => `${row.name} · Damage ${row.damage ?? "Unknown"}${row.rangeText ? ` · ${row.rangeText}` : ""}${row.effect ? ` — ${row.effect}` : ""}`)} />
    <PreviewRows title="Skills" rows={draft.skillLinks.filter((row) => row.linkType === "Skill").map((row) => `${row.skillName}${row.value === null ? "" : `: ${row.value}`}`)} />
    <PreviewRows title="Granted Abilities" rows={draft.skillLinks.filter((row) => row.linkType === "Granted").map((row) => row.skillName)} />
    <PreviewSection title="Behavior & Ecology" empty={false}>{[["Magic / Resonance", core.magicResonanceInteraction], ["Behavior / Tactics", core.behaviorTactics], ["Habitat", core.habitat], ["Diet", core.diet], ["Loot / Harvest", core.lootHarvest], ["Story Hooks", core.storyHooks]].map(([label, value]) => value && <div key={label}><strong>{label}</strong><p>{value}</p></div>)}</PreviewSection>
    <PreviewRows title="Variants" rows={draft.variants.map((row) => `${row.name}${row.description ? ` — ${row.description}` : ""}`)} /><PreviewRows title="Uses" rows={draft.uses.map((row) => `${row.useType}${row.notes ? ` — ${row.notes}` : ""}`)} />
    <PreviewRows title="Purchase Availability" rows={draft.purchaseItemLinks.map((row) => `${row.itemName} · ${row.costCredits === null ? "Cost unknown" : `${row.costCredits.toLocaleString()} credits`}`)} />
  </article>;
}
function PreviewSection({ title, empty, children }: { title: string; empty: boolean; children: React.ReactNode }) { return <section><h4>{title}</h4>{empty ? <p>None recorded.</p> : children}</section>; }
function PreviewRows({ title, rows }: { title: string; rows: string[] }) { return <section><h4>{title}</h4>{rows.length ? <ul>{rows.map((row, index) => <li key={index}>{row}</li>)}</ul> : <p>None recorded.</p>}</section>; }
