import { useEffect, useState } from "react";
import type { SaveItemAggregate } from "../../types/item";

type Props = { draft: SaveItemAggregate | null; saving: boolean; dirty: boolean; feedback: { kind: "success" | "error"; message: string } | null; onChange: (draft: SaveItemAggregate) => void; onSave: () => void; onDelete: () => void };
type Tab = "details" | "weapon" | "armor" | "preview";
const TABS: { id: Tab; label: string }[] = [{ id: "details", label: "Item Details" }, { id: "weapon", label: "Weapon Profile" }, { id: "armor", label: "Armor Profile" }, { id: "preview", label: "Preview" }];
const numberValue = (value: string) => value === "" ? null : Number(value);

export function ItemEditor({ draft, saving, dirty, feedback, onChange, onSave, onDelete }: Props) {
  const [tab, setTab] = useState<Tab>("details");
  const [confirmDelete, setConfirmDelete] = useState(false);
  useEffect(() => { setTab("details"); setConfirmDelete(false); }, [draft?.id]);
  if (!draft) return <section className="skill-editor skill-editor--empty"><p>ITEM EDITOR</p><h2>Select an Item or begin a new one.</h2><span>Only the selected aggregate is loaded into the editor.</span></section>;
  const core = draft.core;
  const setCore = (update: Partial<typeof core>) => onChange({ ...draft, core: { ...core, ...update } });
  return <section className="skill-editor item-editor">
    <header className="skill-editor__header"><div><p>{draft.id ? `ITEM ${draft.id}` : "NEW ITEM DRAFT"}</p><h2>{core.name || "Untitled Item"}</h2><span>{dirty ? "Unsaved changes" : draft.id ? "Saved" : "Not yet persisted"}</span></div><div className="skill-editor__actions">{draft.id && !confirmDelete && <button className="skills-danger-button" type="button" onClick={() => setConfirmDelete(true)}>Delete</button>}<button className="skills-primary-button" type="button" disabled={saving} onClick={onSave}>{saving ? "Saving…" : "Save Item"}</button></div></header>
    {confirmDelete && <div className="skill-editor__delete-confirm" role="alert"><div><strong>Delete {core.name || "this Item"}?</strong><span>Profiles, tags, and purchase relationships will be removed. Linked Creatures remain.</span></div><button className="skills-danger-button" type="button" onClick={onDelete}>Confirm Delete</button><button type="button" onClick={() => setConfirmDelete(false)}>Cancel</button></div>}
    {feedback && <p className={`skill-editor__feedback is-${feedback.kind}`} role="status">{feedback.message}</p>}
    <nav className="skill-editor__tabs" aria-label="Item editor sections">{TABS.map((entry) => <button key={entry.id} type="button" className={tab === entry.id ? "is-active" : ""} onClick={() => setTab(entry.id)}>{entry.label}</button>)}</nav>
    <div className="skill-editor__content">
      {tab === "details" && <div className="catalog-form"><div className="skill-editor__intro"><p>Item identity, catalog placement, and common information are shared by every optional profile.</p></div><div className="catalog-form__grid">
        <label className="is-wide"><span>Name</span><input value={core.name} onChange={(event) => setCore({ name: event.target.value })} /></label>
        <label><span>Catalog Section</span><select value={core.catalogSection} onChange={(event) => setCore({ catalogSection: event.target.value })}><option>Equipment</option><option>Inventory</option></select></label>
        <label><span>Timeline Tag</span><input value={core.timelineTag} onChange={(event) => setCore({ timelineTag: event.target.value })} /></label>
        <label><span>Cost (Credits)</span><input type="number" value={core.costCredits ?? ""} placeholder="Unknown" onChange={(event) => setCore({ costCredits: numberValue(event.target.value) })} /></label>
        <label><span>Weight</span><input type="number" value={core.weight ?? ""} placeholder="Unknown" onChange={(event) => setCore({ weight: numberValue(event.target.value) })} /></label>
        <label><span>Category</span><input value={core.category} onChange={(event) => setCore({ category: event.target.value })} /></label>
        <label><span>Subtype</span><input value={core.subtype} onChange={(event) => setCore({ subtype: event.target.value })} /></label>
        <label className="is-wide"><span>Genre Tags (comma separated)</span><input value={draft.genreTags.join(", ")} onChange={(event) => onChange({ ...draft, genreTags: event.target.value.split(",") })} /></label>
        <label className="is-wide"><span>Effect Description</span><textarea value={core.effectDescription} onChange={(event) => setCore({ effectDescription: event.target.value })} /></label>
        <label className="is-wide"><span>Narrative / Variant Notes</span><textarea value={core.narrativeVariantNotes} onChange={(event) => setCore({ narrativeVariantNotes: event.target.value })} /></label>
      </div></div>}
      {tab === "weapon" && (!draft.weaponProfile ? <div className="catalog-empty"><h3>No Weapon Profile</h3><p>This Item can remain non-weapon content.</p><button className="skills-primary-button" type="button" onClick={() => onChange({ ...draft, weaponProfile: { weaponRole: "Primary", weaponCategory: "", handedness: "", damageType: "", rangeType: "", rangeText: "", damage: null, weaponEffectDescription: "", weaponNarrativeNotes: "", sourceSystem: null, sourceExternalId: null } })}>Add Weapon Profile</button></div> : <div className="catalog-form"><div className="catalog-profile-heading"><p>Weapon mechanics remain optional and do not control catalog placement.</p><button className="skills-danger-button" type="button" onClick={() => onChange({ ...draft, weaponProfile: null })}>Remove Profile</button></div><div className="catalog-form__grid">{[
        ["Weapon Role", "weaponRole"], ["Weapon Category", "weaponCategory"], ["Handedness", "handedness"], ["Damage Type", "damageType"], ["Range Type", "rangeType"], ["Range", "rangeText"],
      ].map(([label, key]) => <label key={key}><span>{label}</span><input value={String(draft.weaponProfile?.[key as keyof typeof draft.weaponProfile] ?? "")} onChange={(event) => onChange({ ...draft, weaponProfile: { ...draft.weaponProfile!, [key]: event.target.value } })} /></label>)}<label><span>Damage</span><input type="number" value={draft.weaponProfile.damage ?? ""} placeholder="Unknown" onChange={(event) => onChange({ ...draft, weaponProfile: { ...draft.weaponProfile!, damage: numberValue(event.target.value) } })} /></label><label className="is-wide"><span>Weapon Effect</span><textarea value={draft.weaponProfile.weaponEffectDescription} onChange={(event) => onChange({ ...draft, weaponProfile: { ...draft.weaponProfile!, weaponEffectDescription: event.target.value } })} /></label><label className="is-wide"><span>Weapon Notes</span><textarea value={draft.weaponProfile.weaponNarrativeNotes} onChange={(event) => onChange({ ...draft, weaponProfile: { ...draft.weaponProfile!, weaponNarrativeNotes: event.target.value } })} /></label></div></div>)}
      {tab === "armor" && (!draft.armorProfile ? <div className="catalog-empty"><h3>No Armor Profile</h3><p>This Item can remain non-armor content.</p><button className="skills-primary-button" type="button" onClick={() => onChange({ ...draft, armorProfile: { areaCovered: "", soak: null, armorCategory: "", armorType: "", encumbrancePenalty: null, armorEffectDescription: "", armorNarrativeNotes: "", sourceSystem: null, sourceExternalId: null } })}>Add Armor Profile</button></div> : <div className="catalog-form"><div className="catalog-profile-heading"><p>Armor mechanics remain optional and can coexist with a Weapon Profile.</p><button className="skills-danger-button" type="button" onClick={() => onChange({ ...draft, armorProfile: null })}>Remove Profile</button></div><div className="catalog-form__grid">{[
        ["Area Covered", "areaCovered"], ["Armor Category", "armorCategory"], ["Armor Type", "armorType"],
      ].map(([label, key]) => <label key={key}><span>{label}</span><input value={String(draft.armorProfile?.[key as keyof typeof draft.armorProfile] ?? "")} onChange={(event) => onChange({ ...draft, armorProfile: { ...draft.armorProfile!, [key]: event.target.value } })} /></label>)}<label><span>Soak</span><input type="number" value={draft.armorProfile.soak ?? ""} placeholder="Unknown" onChange={(event) => onChange({ ...draft, armorProfile: { ...draft.armorProfile!, soak: numberValue(event.target.value) } })} /></label><label><span>Encumbrance Penalty</span><input type="number" value={draft.armorProfile.encumbrancePenalty ?? ""} placeholder="Unknown" onChange={(event) => onChange({ ...draft, armorProfile: { ...draft.armorProfile!, encumbrancePenalty: numberValue(event.target.value) } })} /></label><label className="is-wide"><span>Armor Effect</span><textarea value={draft.armorProfile.armorEffectDescription} onChange={(event) => onChange({ ...draft, armorProfile: { ...draft.armorProfile!, armorEffectDescription: event.target.value } })} /></label><label className="is-wide"><span>Armor Notes</span><textarea value={draft.armorProfile.armorNarrativeNotes} onChange={(event) => onChange({ ...draft, armorProfile: { ...draft.armorProfile!, armorNarrativeNotes: event.target.value } })} /></label></div></div>)}
      {tab === "preview" && <article className="catalog-preview"><header><p>{core.catalogSection}</p><h3>{core.name || "Untitled Item"}</h3><span>{core.category || "Uncategorized"}{core.subtype ? ` · ${core.subtype}` : ""}</span></header><dl><div><dt>Cost</dt><dd>{core.costCredits === null ? "Unknown" : `${core.costCredits.toLocaleString()} credits`}</dd></div><div><dt>Weight</dt><dd>{core.weight === null ? "Unknown" : core.weight}</dd></div><div><dt>Genres</dt><dd>{draft.genreTags.map((tag) => tag.trim()).filter(Boolean).join(", ") || "None"}</dd></div></dl>{core.effectDescription && <section><h4>Effect</h4><p>{core.effectDescription}</p></section>}{draft.weaponProfile && <section><h4>Weapon Profile</h4><p>{draft.weaponProfile.weaponRole} · {draft.weaponProfile.weaponCategory || "Uncategorized"} · Damage {draft.weaponProfile.damage ?? "Unknown"}</p></section>}{draft.armorProfile && <section><h4>Armor Profile</h4><p>{draft.armorProfile.armorCategory || "Uncategorized"} · Soak {draft.armorProfile.soak ?? "Unknown"}</p></section>}</article>}
    </div>
  </section>;
}
